### ISSUE TITLE
Links to Natasha's write ups 

### ISSUE THREAD

**Issue by yas375** [AndrewJByrne/cocoaconf-2016-seattle-resources#1]
Thanks for putting this all together!

You might also find useful to link to Natasha's write ups about what she was talking about at the conference:
- https://www.natashatherobot.com/protocol-oriented-networking-in-swift/
- https://www.natashatherobot.com/protocol-oriented-views-in-swift/

P.S. also there is a typo in her name ;)

**Comment by AndrewJByrne** [comment]
@yas375 Thanks for the updates and for spotting the typo :-) I've updated the list.
